feat(#64): Upgraded example and plugin library to use the new GPA 8 s…
AS-Devs/signalr_flutter pull request #65
Opened 2024-05-17 08:20 UTC by devaronius

In Flutter 3.16, support was added for applying these plugins with Gradle's [declarative plugins {} block](https://docs.gradle.org/8.5/userguide/plugins.html#sec:plugins_block) (also called the Plugin DSL) and it is now the recommended approach. Since Flutter 3.16, projects generated with flutter create use the Plugin DSL to apply Gradle plugins. Projects created with versions of Flutter prior to 3.16 need to be migrated manually.

https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply

## Solution:

- [#64] upgraded GPA (Android Gradle Plugin) to version 8 to comply to deprication of the old flutter gradle implementation.

- [#64] Plugin now requires the following:
    - Flutter >=3.19.0
    - Dart >=3.3.0
    - compileSDK 33 for Android part
    - Java 17 for Android part
    - Gradle 8.0 for Android part

2024-05-25 07:03 UTC, AyonAB commented on example/pubspec.yaml
> +  flutter: ^3.19.0
Remove flutter version upper bound with lower bound. Probably use `flutter: ">=3.19.0"`.

2024-05-25 07:20 UTC, AyonAB requested changes

2024-05-25 07:20 UTC, AyonAB commented on example/pubspec.yaml
> +  flutter: ^3.19.0
Remove flutter version upper bound with lower bound. Probably use `flutter: ">=3.19.0"`.

2024-05-25 07:20 UTC, AyonAB commented on example/pubspec.yaml
> +  sdk: ^3.2.0
Do the same for SDK also. Do not constraint upper bound, constraint lower bound.

2024-05-25 07:20 UTC, AyonAB commented on pubspec.yaml
> +  flutter: ^3.19.0
Remove flutter version upper bound with lower bound. Probably use `flutter: ">=3.19.0"`.

2024-05-25 07:20 UTC, AyonAB commented on pubspec.yaml
> +  sdk: ^3.2.0
Do the same for SDK also. Do not constraint upper bound, constraint lower bound.

2024-05-27 08:45 UTC, devaronius commented
All requested changes have been completed

2024-06-02 13:49 UTC, AyonAB approved these changes

2024-06-02 13:52 UTC, merged